In [21]:
import numpy as np
import pandas as pd

lst = [1,2,3,4.5]
lst

In [4]:
arr1 = np.array(lst)
arr1

NameError: name 'np' is not defined

In [6]:
lst2 = [[1,2,3],[4,5,6]]
lst2

[[1, 2, 3], [4, 5, 6]]

In [8]:
arr2 = np.array(lst2)
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
arr2 = np.array([[1,2,3],[4,5,6]])

## 2.2 shape, dtype, ndim

### Как измерить длину массива?

In [10]:
len(lst)

4

In [11]:
len(arr1)

4

In [12]:
len(arr2) #количество вложенных списков

2

In [14]:
arr2.shape
#Out: (2 (количество подмассивов),3 (количество элементов в каждом массиве))

(2, 3)

In [16]:
arr2.ndim
# показывает вложенность

2

## 2.3 Типы данных и их преобразование, арифметика, доступ к элементам

### Тип данных

In [17]:
arr1.dtype

dtype('float64')

In [18]:
arr3 = np.array([1,2,3,'a'])

In [22]:
arr3.dtype

dtype('<U11')

### Инициализация

#### c 0

In [20]:
lst = [0,0,0,0,0,0,0]

In [23]:
arr1 = np.zeros(5)
arr1

array([0., 0., 0., 0., 0.])

In [25]:
arr2 = np.zeros((3,5, 2))
arr2

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

#### с определенными значениями

In [27]:
arr1 = np.ones(5)
arr1

array([1., 1., 1., 1., 1.])

In [28]:
arr2 = np.ones((5,3))
arr2

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [29]:
arr3 = np.full(5, -1)
arr3

array([-1, -1, -1, -1, -1])

In [32]:
arr4 = np.full((5,3), -1)
arr4

array([[-1, -1, -1],
       [-1, -1, -1],
       [-1, -1, -1],
       [-1, -1, -1],
       [-1, -1, -1]])

#### с какой-то последовательностью

In [33]:
lst = list(range(10))
lst

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [34]:
arr1 = np.arange(10)
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### Типы данных

#### 1

In [5]:
arr1 = np.array([1,2,3,4,5])
arr1.dtype

dtype('int32')

In [8]:
arr1 = np.array([1,2,3,4,5], dtype=np.float64)
arr1.dtype

dtype('float64')

In [9]:
arr2 = arr2.astype(np.int64)
arr2

array([1, 2, 3, 4, 5], dtype=int64)

In [11]:
arr1 = np.array([1.1,2.2,3.3,4.4,5.5])
arr1.dtype

dtype('float64')

In [12]:
arr1.astype(np.int64)

array([1, 2, 3, 4, 5], dtype=int64)

In [13]:
arr1 = np.array(['1.1','2.2','3.3','4.4','5.5'])
arr1

array(['1.1', '2.2', '3.3', '4.4', '5.5'], dtype='<U3')

In [14]:
arr2 = arr1.astype(np.float64)
arr2

array([1.1, 2.2, 3.3, 4.4, 5.5])

#### 2

In [8]:
m1 = np.arange(10)
m1.dtype

dtype('int32')

In [18]:
m2 = np.array([1.1,2.2,3.3,4.4,5.5])
m2.dtype

dtype('float64')

In [19]:
m3 = m1.astype(m2.dtype)
m3.dtype

dtype('float64')

### Арифметика

#### умножение

In [21]:
lst = [1,2,3,4]

In [22]:
lst * 2

[1, 2, 3, 4, 1, 2, 3, 4]

In [26]:
m1 = np.array(lst)

In [27]:
m1 * 2

array([2, 4, 6, 8])

#### сложение

In [28]:
lst + 1

TypeError: can only concatenate list (not "int") to list

In [29]:
m1 + 1

array([2, 3, 4, 5])

### Сравнение

In [31]:
temp_1006 = [36.6, 35.8, 38.7]
temp_1106 = [36.6, 36.6, 36.6]

In [32]:
temp_1106>temp_1006

True

In [34]:
m1_1006 = np.array(temp_1006)
m2_1106 = np.array(temp_1106)

In [35]:
m2_1106>m1_1006

array([False,  True, False])

In [38]:
arr = np.arange(10,20)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

## 2.5 Двумерные и трехмерные массивы. Учимся применять индексы

#### работаем в срезе, не меняя исходный массив

In [17]:
m1 = np.arange(10)

In [18]:
m2=m1[3:6].copy() #чтобы не менялся элемент в исходном списке
m2

array([3, 4, 5])

In [19]:
m2[0]=0
m2

array([0, 4, 5])

In [20]:
m1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
m2d = np.array([[1,2,3],[4,5,6]])
m2d

array([[1, 2, 3],
       [4, 5, 6]])

#### индексы в двумерном массиве

In [25]:
m2d[1][1]

5

In [34]:
m2d[1,1]

5

In [4]:
m2d = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12], [13,14,15,16], [17,18,19,20]])
m2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [44]:
m2d[2:4]

array([[ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [39]:
m2d[1:]

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [40]:
m2d[:4]

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [43]:
m2d[:,0]

array([ 1,  5,  9, 13, 17])

In [45]:
m2d[:,2]

array([ 3,  7, 11, 15, 19])

In [46]:
m2d[:, 1:3]

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15],
       [18, 19]])

In [47]:
m2d[:2, :2]

array([[1, 2],
       [5, 6]])

In [48]:
m2d[-2:, -2:]

array([[15, 16],
       [19, 20]])

In [50]:
m2d[1:4, 1:3]

array([[ 6,  7],
       [10, 11],
       [14, 15]])

#### индексы в трехмерном массиве

In [27]:
m3d = np.array([[[1,2,3], [4,5,6]],[[7,8,9],[10,11,12]]])
m3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [28]:
m3d.shape
# Out: (2 - 2 двумерных массива, 2 - количество строк в двумерном массиве,3 - количество столбцов)

(2, 2, 3)

In [32]:
m3d[1,1,1]

11

In [33]:
m3d[0] = 0
m3d

array([[[ 0,  0,  0],
        [ 0,  0,  0]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

#### с помощью маски

In [51]:
arr = np.arange(5)

In [53]:
mask= [True, True, False, False, True]

In [54]:
arr[mask]

array([0, 1, 4])

In [2]:
m2d[2:3]

NameError: name 'm2d' is not defined

In [4]:
m2d[:1]+m2d[1:2]

array([[ 6,  8, 10, 12]])

In [7]:
m2d[:, :1]

array([[ 1],
       [ 5],
       [ 9],
       [13],
       [17]])

In [12]:
np.sum(m2d[:, 2:3], m2d[:, :1])

TypeError: only integer scalar arrays can be converted to a scalar index

## 2.7 Маска и слайсинг вместе, прихотливая индексация, а еще reshape

**Задача: вывести график посещений Андрея по выходным**

In [11]:
visits = np.array([
    [1,2,1,0,0,1,1],
    [0,0,1,0,3,1,2],
    [2,1,0,2,0,2,1],
    [1,2,1,0,1,1,1],
    [1,2,1,0,0,1,0]
])
users = np.array(['Андрей', 'Иван', 'Николай', 'Александр', 'Андрей'])

In [20]:
mask = users == 'Андрей'
mask

array([ True, False, False, False,  True])

In [15]:
visits[mask, 5:]

array([[1, 1],
       [1, 0]])

**Задача: вывести всех кроме Андрея**

1 вариант

In [18]:
mask2 = users != 'Андрей'
mask2

array([False,  True,  True,  True, False])

In [17]:
visits[mask, 5:]

array([[1, 2],
       [2, 1],
       [1, 1]])

2 вариант

In [21]:
mask

array([ True, False, False, False,  True])

In [23]:
visits[~mask, 5:]

array([[1, 2],
       [2, 1],
       [1, 1]])

**Задача: вывести графики Ивана и Александра**

In [24]:
mask1 = users == 'Иван'
mask1

array([False,  True, False, False, False])

In [25]:
mask2 = users == 'Александр'
mask2

array([False, False, False,  True, False])

In [28]:
mask = mask1 | mask2
mask

array([False,  True, False,  True, False])

In [29]:
visits[mask]

array([[0, 0, 1, 0, 3, 1, 2],
       [1, 2, 1, 0, 1, 1, 1]])

### прихотливая индексация

In [7]:
m2d 

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [32]:
m2d[[0,2,4]]

array([[ 1,  2,  3,  4],
       [ 9, 10, 11, 12],
       [17, 18, 19, 20]])

In [6]:
m2d[[0,2,4],[1,2,3]] #создание одномерного массива с элементами, находящимися по указанным индексам

array([ 2, 11, 20])

In [36]:
m2d[[0,2,4]][:,[1,2,3]] #вытягивание определенных строк и столбцов

array([[ 2,  3,  4],
       [10, 11, 12],
       [18, 19, 20]])

**Задача: разложить одномер. массив в матрицу 10*5**

In [18]:
m1 = np.arange(50)
m1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [19]:
m1.reshape((10,5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

**Задача: разложить одномер. массив в трехмерный массив**

In [20]:
m1.reshape((5,2,5))

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]],

       [[30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39]],

       [[40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49]]])

## 2.9 Еще о reshape, транспонирование, унарные и бинарные функции

In [21]:
# reshape не создает новый массив, а меняет существующий по причине большого потребления памяти

### Транспонирование

In [22]:
m1 = np.arange(21).reshape((3,7))
m1

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20]])

In [23]:
m1.T

array([[ 0,  7, 14],
       [ 1,  8, 15],
       [ 2,  9, 16],
       [ 3, 10, 17],
       [ 4, 11, 18],
       [ 5, 12, 19],
       [ 6, 13, 20]])

In [25]:
m2 = m1.transpose()

In [26]:
m2[0] = 0

In [27]:
m2

array([[ 0,  0,  0],
       [ 1,  8, 15],
       [ 2,  9, 16],
       [ 3, 10, 17],
       [ 4, 11, 18],
       [ 5, 12, 19],
       [ 6, 13, 20]])

In [28]:
m1
# транспонируется не новый массив, изменяется старый

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 0,  8,  9, 10, 11, 12, 13],
       [ 0, 15, 16, 17, 18, 19, 20]])

### Унарные функции
#### принимают один массив и работают поэлементно

In [44]:
m1 = np.array([-12.1,4.6,6.5,8.9, np.nan])

In [45]:
m1+1

array([-11.1,   5.6,   7.5,   9.9,   nan])

In [46]:
m2 = m1**2
m2

array([146.41,  21.16,  42.25,  79.21,    nan])

In [47]:
# не сохраняются изменения в исходном массиве
np.sqrt(m2)

array([12.1,  4.6,  6.5,  8.9,  nan])

In [53]:
np.abs(m1, out = m1)
# изменение в исходном массиве

array([12.1,  4.6,  6.5,  8.9,  nan])

In [49]:
np.round(m1)

array([-12.,   5.,   6.,   9.,  nan])

In [50]:
np.ceil(m1)

array([-12.,   5.,   7.,   9.,  nan])

In [51]:
np.floor(m1)

array([-13.,   4.,   6.,   8.,  nan])

In [52]:
np.isnan(m1)

array([False, False, False, False,  True])

### Бинарные функции
#### принимают два массива

In [75]:
m1 = np.array([1,2,3,4])

In [76]:
m2 = np.array([0,3,1,6])

In [77]:
# определить, какой из двух элементов больше
np.maximum(m1,m2)

array([1, 3, 3, 6])

In [57]:
np.minimum(m1,m2)

array([0, 2, 1, 4])

In [61]:
# сложить элементы между собой
np.add(m1,m2)

ValueError: operands could not be broadcast together with shapes (5,) (4,) 

In [64]:
# вычесть один ассив из другого
np.subtract(m1,m2)

array([ 1, -1,  2, -2])

In [66]:
np.multiply(m1,m2)

array([ 0,  6,  3, 24])

In [67]:
m1/m2


C:\Users\1645295\AppData\Local\Temp/ipykernel_17100/3408699618.py:1: RuntimeWarning: divide by zero encountered in true_divide
  m1/m2


array([       inf, 0.66666667, 3.        , 0.66666667])

In [68]:
np.isinf(m1/m2)

C:\Users\1645295\AppData\Local\Temp/ipykernel_17100/3903444778.py:1: RuntimeWarning: divide by zero encountered in true_divide
  np.isinf(m1/m2)


array([ True, False, False, False])

In [69]:
np.divide(m1,m2)

C:\Users\1645295\AppData\Local\Temp/ipykernel_17100/1229016130.py:1: RuntimeWarning: divide by zero encountered in true_divide
  np.divide(m1,m2)


array([       inf, 0.66666667, 3.        , 0.66666667])

In [70]:
m1

array([1, 2, 3, 4])

In [72]:
m1.shape

(4,)

## 2.11 Логические функции и функция в функции, а еще where и статистика

In [78]:
# узнать, какие элементы 1 массива больше
np.greater(m1,m2)
m1 > m2


array([ True, False,  True, False])

In [79]:
mask = np.greater(m1,m2)
m1[mask]

array([1, 3])

In [82]:
np.greater_equal(m1,m2)
m1 >=m2

array([ True, False,  True, False])

In [83]:
# узнать, какие элементы 1 массива меньше
np.less(m1,m2)
m1 < m2


array([False,  True, False,  True])

In [84]:
np.less_equal(m1,m2)
m1 <= m2

array([False,  True, False,  True])

In [87]:
# узнать, какие элементы равны между собой
np.equal(m1,m2)
m1 == m2

array([False, False, False, False])

### where

In [88]:
# Задача: если элемент > 0 - +100
# если элемент < 0 - -100


In [98]:
m1 = np.array([2,-3,4,-6,7,-8])

In [93]:
mask_greater = m1 > 0

In [92]:
mask_less = m1 < 0

In [94]:
m1[mask_greater] = 100
m1[mask_less] = -100
m1

array([ 100, -100,  100, -100,  100, -100])

In [95]:
np.where(m1 > 0, 100, -100)
# условие, если выполняется, если не выполняется

array([ 100, -100,  100, -100,  100, -100])

In [99]:
# Задача: занулить отрицательные значения
np.where(m1 < 0, 0, m1)

array([2, 0, 4, 0, 7, 0])

### статистика

In [102]:
m1 = np.arange(6)
m1

array([0, 1, 2, 3, 4, 5])

In [101]:
np.sum(m1)

15

In [104]:
m1.sum()

15

In [103]:
np.mean(m1)

2.5

In [105]:
m1.mean()

2.5

In [107]:
m2d = np.arange(12).reshape((2,6))
m2d

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [111]:
# axis - по какой оси считать (1 - по строке, 0 - по столбцам)
m2d.sum(axis = 0)

array([ 6,  8, 10, 12, 14, 16])

In [116]:
m2d.min(axis = 0)


array([0, 1, 2, 3, 4, 5])

In [113]:
m2d.max()

11

In [117]:
np.std(m2d)

3.452052529534663

In [118]:
np.var(m2d)

11.916666666666666

In [119]:
# индекс минимального элемента
np.argmin(m2d)

0

In [120]:
np.argmax(m2d)

11

## 2.13 Функции any, all, sort, unique, in1d

###  any, all

In [4]:
bools_arr1 = np.array([True, True, False, True])
bools_arr2 = np.array([False, False, False, False])
bools_arr3 = np.array([True, True, True, True])

In [5]:
bools_arr1.any() 
# хотя бы одно True

True

In [7]:
bools_arr3.all()
# все были True

True

### sort

In [8]:
m1 = np.array ([1,8,2,-1,0,6])

In [10]:
m1.sort()
# сортирует уже существующий массив
m1

array([-1,  0,  1,  2,  6,  8])

In [13]:
m2d = np.array([[1,5,0,-2],[6,2,0,-8],[-2,4,8,12]])
m2d

array([[ 1,  5,  0, -2],
       [ 6,  2,  0, -8],
       [-2,  4,  8, 12]])

In [14]:
m2d.sort(axis = 0)
# по умолчанию по строкам (axis = 1)
m2d

array([[-2,  2,  0, -8],
       [ 1,  4,  0, -2],
       [ 6,  5,  8, 12]])

### unique

In [4]:
names = np.array(['Ivan', 'Andrey', 'Roman', 'Andrey', 'Sergey', 'Ivan'])
# проверить на дубликаты

In [17]:
unames = np.unique(names)
len(unames)

4

### in1d

In [5]:
np.in1d(names, ['Roman','Andrey'])

array([False,  True,  True,  True, False, False])

### random 

In [7]:
np.random.randint(1,10,size=(5,4))

array([[4, 4, 6, 5],
       [2, 9, 8, 8],
       [8, 1, 6, 5],
       [9, 2, 1, 9],
       [2, 4, 7, 9]])

## 2.14 Функции permutation и shuffle. Сохранение массива в файл

### permutation

In [8]:
np.random.randint(1,10,size=10)

array([2, 4, 8, 7, 7, 2, 5, 9, 2, 8])

In [9]:
np.random.permutation(10)
# создание перемешанного массива

array([4, 7, 8, 6, 3, 5, 0, 2, 1, 9])

In [10]:
m1 = np.arange(10)
m1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### shuffle

In [21]:
np.random.shuffle(m1)
m1
# перемешивание в существующем массиве

array([3, 8, 5, 1, 2, 6, 7, 4, 9, 0])

In [24]:
np.random.randn(10)
# из нормального распределения

array([-1.75731741, -0.61087804, -0.21687266,  0.00332464, -0.91989858,
       -0.18522136, -0.80978199,  0.76218867,  1.08044716,  1.45362637])

In [25]:
np.random.randn(2,5)
# генерируется двумерный массив

array([[-0.78350422,  0.68408908,  0.81658601, -0.14832388,  0.09644471],
       [-0.50129104, -1.59027557, -0.27416526, -1.18450872, -1.32574938]])

### cохранение массива в файл

In [26]:
m1

array([3, 8, 5, 1, 2, 6, 7, 4, 9, 0])

In [27]:
np.save('my_array', m1)
# .npy

In [29]:
np.load('my_array.npy')

array([3, 8, 5, 1, 2, 6, 7, 4, 9, 0])

In [42]:
m2 = np.arange(10,20)
np.random.shuffle(m2)
m2

array([16, 18, 15, 19, 11, 17, 13, 12, 14, 10])

In [43]:
np.savez('arrays', name1=m1, name2=m2)
# .npz

In [46]:
m12 = np.load('arrays.npz')


array([3, 8, 5, 1, 2, 6, 7, 4, 9, 0])

In [47]:
m12['name1']


array([3, 8, 5, 1, 2, 6, 7, 4, 9, 0])

In [48]:
m12['name2']

array([16, 18, 15, 19, 11, 17, 13, 12, 14, 10])

In [49]:
np.savez_compressed('comp_arrays', key1=m1, key2=m2)

In [51]:
arch = np.load('comp_arrays.npz')

In [52]:
arch['key1']

array([3, 8, 5, 1, 2, 6, 7, 4, 9, 0])

In [22]:
arch['key2']

NameError: name 'arch' is not defined